# --- 1. LA DEMANDE DE STOCKAGE ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# --- 2. LE DÉPLOIEMENT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bindkey-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bindkey
  template:
    metadata:
      labels:
        app: bindkey
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        # --- LE SERVEUR RUST ---
        - name: server
          image: ghcr.io/bindkey-project/bindkey-server/bindkey-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgres://bindkey:bindkey@localhost:5432/bindkey"

        # --- LA BASE DE DONNÉES POSTGRES ---
        - name: db
          image: ghcr.io/bindkey-project/bindkey-server/bindkey-db:latest
          ports:
            - containerPort: 5432
          # ON REPRÉCISE LES ENV POUR LA DB
          env:
            - name: POSTGRES_USER
              value: "bindkey"
            - name: POSTGRES_PASSWORD
              value: "bindkey"
            - name: POSTGRES_DB
              value: "bindkey"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
# --- 3. LE SERVICE (Pour accéder à l'API) ---
apiVersion: v1
kind: Service
metadata:
  name: bindkey-service
spec:
  type: NodePort
  selector:
    app: bindkey
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080