# ─────────────────────────────────────────────
# Informations générales du projet Rust
# ─────────────────────────────────────────────
[package]
name = "bindkey-server"       # Nom du binaire généré (bindkey-server)
version = "0.1.0"             # Version de ton application
edition = "2021"              # Version du langage Rust utilisée (la plus récente)


# ─────────────────────────────────────────────
# Dépendances Rust utilisées par le projet
# ─────────────────────────────────────────────
[dependencies]

# Framework web utilisé pour créer l'API HTTP (routes, JSON, extracteurs...)
axum = "0.7"

# Runtime asynchrone indispensable pour Axum + SQLx
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }

# Système de logs moderne
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

# Lecture automatique des variables dans le fichier .env
dotenvy = "0.15"

# ORM async pour PostgreSQL + support UUID/chrono + macros + migrations
# On désactive les "default-features" pour ne garder que le strict nécessaire
# On configure sqlx sans les drivers par défaut
sqlx = { version = "0.8", default-features = false, features = ["postgres", "runtime-tokio", "tls-rustls", "uuid", "chrono", "migrate", "macros"] }


# Sérialisation/désérialisation JSON (Serialize / Deserialize)
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

# Gestion des UUID (id des users, devices, etc.)
uuid = { version = "1.19.0", features = ["v4", "serde"] }

# Gestion des dates/timestamps PostgreSQL (TIMESTAMPTZ)
chrono = { version = "0.4.42", features = ["serde"] }
tower = { version = "0.5.3", features = ["util"] }

[lib]
name = "bindkey_server"  # J'utilise l'underscore ici (_)
path = "src/main.rs"

[[test]]
name = "bindkey_tests"
path = "Tests/bindkey_tests.rs"
[[test]]
name = "disk_tests"
path = "Tests/disk_tests.rs"
[[test]]
name = "volume_tests"
path = "Tests/volume_tests.rs"
[[test]]
name = "session_tests"
path = "Tests/session_tests.rs"
[[test]]
name = "mount_tests"
path = "Tests/mount_tests.rs"
[[test]]
name = "permission_tests"
path = "Tests/permission_tests.rs"