# ─────────────────────────────────────────────
# Informations générales du projet Rust
# ─────────────────────────────────────────────
[package]
name = "bindkey-server"       # Nom du binaire généré (bindkey-server)
version = "0.1.0"             # Version de ton application
edition = "2024"              # Version du langage Rust utilisée (la plus récente)


# ─────────────────────────────────────────────
# Dépendances Rust utilisées par le projet
# ─────────────────────────────────────────────
[dependencies]

# Framework web utilisé pour créer l'API HTTP (routes, JSON, extracteurs...)
axum = "0.7"

# NOUVEAU : Serveur gérant le HTTPS nativement
axum-server = { version = "0.7", features = ["tls-rustls"] }
# Ajoute cette ligne dans ton Cargo.toml sous [dependencies]
rustls = "0.23"

# Runtime asynchrone indispensable pour Axum + SQLx
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }

# Système de logs moderne
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

# Lecture automatique des variables dans le fichier .env
dotenvy = "0.15"

# ORM async pour PostgreSQL + support UUID/chrono + macros + migrations
sqlx = { version = "0.8", default-features = false, features = ["postgres", "runtime-tokio", "tls-rustls", "uuid", "chrono", "migrate", "macros"] }


# Sérialisation/désérialisation JSON (Serialize / Deserialize)
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

# Gestion des UUID (id des users, devices, etc.)
uuid = { version = "1.19.0", features = ["v4", "serde"] }

# Gestion des dates/timestamps PostgreSQL (TIMESTAMPTZ)
chrono = { version = "0.4.42", features = ["serde"] }
tower = { version = "0.5.3", features = ["util"] }
ran = "2.0.1"
# Génération de valeurs aléatoires sécurisées
rand = "0.9.2"

# Pour générer des certificats TLS auto-signés
rcgen = "0.13"
ring = "0.17"
# Chiffrement AES-256-GCM (Chiffrement des hashs)
aes-gcm = "0.10.3"
# Pour l'encodage des données chiffrées en texte stockable
base64 = "0.22"

# Hash sécurisé des secrets (mots de passe, etc.)
argon2 = "0.5"

# Gestion du temps
time = "0.3.47"

hex = "0.4"
ed25519-dalek = "2.2.0"
reqwest = { version = "0.13.1", features = ["json"] }
axum-test = "16.4.0"
sha2 = "0.10.9"
p256 = { version = "0.13", features = ["ecdsa"] }
ecdsa = "0.16"
thiserror = "2.0.18"


[lib]
name = "bindkey_server"
path = "src/lib.rs"    # On sépare la logique (lib) du point d'entrée (bin)

[[bin]]
name = "bindkey-server"
path = "src/main.rs"   # Le binaire contient uniquement le démarrage du serveur

[[test]]
name = "bindkey_tests"
path = "Tests/bindkey_tests.rs"


[features]
# On crée une feature "skip-auth"
skip-auth = []


[dev-dependencies]
# On force l'activation de la feature pour tout ce qui est dans le dossier Tests/
bindkey-server = { path = ".", features = ["skip-auth"] }

