version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bindkey-db
    restart: always
    environment:
      POSTGRES_USER: bindkey
      POSTGRES_PASSWORD: bindkey
      POSTGRES_DB: bindkey
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
