version: "3.9"

services:
  bindkey-db:
    image: postgres:16
    container_name: bindkey-db
    restart: always
    environment:
      POSTGRES_USER: bindkey
      POSTGRES_PASSWORD: bindkey
      POSTGRES_DB: bindkey
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  sqlx:
    image: rust:latest
    container_name: sqlx-runner
    working_dir: /app
    volumes:
      - ./src:/app
    environment:
      DATABASE_URL: postgres://bindkey:bindkey@bindkey-db:5432/bindkey
    depends_on:
      - bindkey-db
    command: >
      bash -c "
        rustup toolchain install stable &&
        cargo install sqlx-cli --no-default-features --features postgres &&
        sqlx migrate run
      "

volumes:
  pgdata:

